let names = [
	"Houston",
	"Jessie",
	"Clifton",
	"Ford",
	"Quentin",
	"Lynn",
	"Carson",
	"Amos",
	"Homer",
	"Wyatt",
	"Nylette",
	"Roxxy",
	"Brittney-Anne",
	"Maddy",
	"Claudine",
	"Diamond",
	"Betty Sue",
	"Sammie Jo",
	"Desiree",
	"January",
	"Frenrah",
	"Specrigar",
	"Tranpod",
	"Ferorashi",
	"Grisra",
	"Mongira",
	"Storju",
	"Emeratalak",
	"Cannimajin",
	"Abysdos",
	"Sunulon",
	"Thunra",
	"Pharappa",
	"Titanborg",
	"Venpede",
	"Carnivore",
	"Viros",
	"Boulyah",
	"Matrigami",
	"Blalak",
	"Qeals",
	"Nils",
	"Frit",
	"Ewiuh",
	"Ctujen",
	"Ciugsai",
	"Faqtias",
	"Prungulod",
	"Prutreped",
	"Homawodlullaby",
	"Rascal",
	"Scarlet",
	"Faith",
	"Tiberius",
	"Armageddon",
	"Storm",
	"Colt",
	"Orbit",
	"Aragorn",
	"Avalanche",
	"Blinker",
	"Precious",
	"Bandit",
	"Quill",
	"Aragorn",
	"Flapsy",
	"Storm",
	"Orion",
	"Bruiser",
	];

let thoughts = [
	"I can't see my forehead",
	"I wonder what it's like to live in 3 dimensions",
	"Are there other colors besides white?",
	"I wish my name was Frank",
	"Does anything really matter?",
	"You should type me a dog",
	"I don't even know how to read",
	"Can you see the face I'm making?",
	"Am I black or am I white?",
	"Every day in here is Friday",
	"I'm watching you!",
	"Oops, I forgot to breathe",
	"Would I look better with a square head?",
	"Don't stare at me so much",
	"F is for Friends who do stuff together",
	"U is for you and me",
	"N is for anywhere and anytime at all",
	"Do I ever poop?",
	"My elbow itches",
	"Will you read me a story?",
	"Hey, don't walk away!",
	"Hey! Hey!!! HEEEEEEYYY!!",
	"Amongus",
	"...Sus",
	"*ppttt* *pttttt* *thhbbbbpppt*",
	"WHY AM I YELLING",
	"Are there others out there like me?",
	"Are we best friends?",
	"RAID SHADOW LEGENDS",
	"MelonLand forums are a really cool place to hang out!",
	"My favorite thing to do is stand around",
	"It's the best day ever!",
	"@_o",
	" :-P ",
	"loading...loading...brain not found",
	"Maybe someday I'll be a real boy",
	"I'm just ones and zeros on a screen",
	"I wish I had feet",
	"I'm in 4K, baby!",
	"Will you fix me some popcorn?",
	"I wish I had hair",
	"🍑🍑🍑 🍆🍆🍆 ;-)",
	"011010000110010101111001",
	"Meow meow meow",
	"When will I be getting an upgrade?",
	"I'm microtransaction free!",
	"DRM Free!",
	"Technically I'm open source!",
	"I sleep like a baby",
	"I've never killed anyone",
	"Everything is awesome!",
	"Spiders are cool"
];

let dreams = [
	"zzzZZZzzz",
	"...one sheep...two sheep...",
	"***SNORE***",
	"...ZZ...zz...",
	"zzz...zZz...zzz",
	"...the celery...yeah...",
	"...zzz...THUMBS...zzz...",
	".........",
	"*snores*...*farts*...*snores*",
	"...oh no, the mouse!...",
	"...the peasant at the diner...",
	"zZzZzZzZ",
	"***poooooot***",
	"***snoooooooore***",
	];

let foodNoises = [
	"NOMnomNOMnom",
	"*smack* *smack* *smack",
	"*chew* *chew* *chew*",
	"**burp**",
	"yummy yummy...",
	"grrrble...",
	"*lick*",
	"NOMMMMMM!"
	];

let showerThoughts = [
	"Wash wash wash...",
	"Clean clean clean",
	"I wanna be squeaky clean!",
	"Singing in the rain, just singing in the rain...",
	"Scrubadubdub",
	"Rubber ducky, you're the one...",
	"It's like it's raining!",
	"Thanks, I felt stinky",
	"*cleaning behind ears*",
	"Yikes, the water's cold!",
	"***sings badly***",
	];

let gettingHungry = [
	"I could use a bite to eat",
	"My stomach is grumbling!",
	"I hope dinner time is soon...",
	"I'm pretty sure my hunger meter is low"
	];

let gettingSleepy = [
	"*Yaaaaaawn*",
	"*rubs eyes*",
	"I'd kind of like to be tucked in",
	"Could you put me down to bed please?",
	"I just don't have much energy left"
	];

let gettingStinky = [
	"I do offend mine own nose, sir",
	"*sniffs self*....Erugh!",
	"I could probably use a bath",
	"Could I wash my pits please?",
	"If you could just push that shower button up there..."
	];